spring:
  application:
    name: order-service
  profiles:
    active: local

server:
  port: 8081

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    healthcheck:
      enabled: true

logging:
  level:
    org:
      springframework: DEBUG

app:
  lang: "Kotlin!"

